const states = {
  "000": {
      code: "000",
      adjective: "Elemental",
      adjectivo: "Elemental",
      concept: "Serenity",
      concepto: "Serenidad",
      archetype: "Monk",
      arquetipo: "Monge",
      colour: "Dark",
      colour2: "Charcoal",
      color: "Negro",
      mbti: "I--P",
      location: "Wilderness",
      localidad: "Naturaleza",
      map: "Retreat, Open Range, Getaway",
      mapa: "Camp Abierto, Retiro, Excursion"
  },
  "001": {
      code: "001",
      adjective: "Inspirational",
      adjectivo: "Inspiracional",
      concept: "Empathy",
      concepto: "Empatía",
      archetype: "Aide",
      arquetipo: "Acompañante",
      colour: "Dark Blue",
      colour2: "Navy",
      color: "Azul Oscuro",
      mbti: "-NFP",
      location: "Garden",
      localidad: "Jardín",
      map: "Botanical Garden, Zoo, Fair",
      mapa: "Jardín Botánico, Zoológico, Feria"
  },
  "002": {
      code: "002",
      adjective: "Sentimental",
      adjectivo: "Sentimental",
      concept: "Feeling",
      concepto: "Sentimiento",
      archetype: "Poet",
      arquetipo: "Poeta",
      colour: "Pure Blue",
      colour2: "Indigo",
      color: "Azul Puro",
      mbti: "INFP",
      location: "Auditorium",
      localidad: "Auditorio",
      map: "Concert Hall, Theatre, Opera House",
      mapa: "Recital, Teatro, Ópera"
  },
  "010": {
      code: "010",
      adjective: "Conceptual",
      adjectivo: "Conceptual",
      concept: "Knowledge",
      concepto: "Conocimiento",
      archetype: "Researcher",
      arquetipo: "Investigador",
      colour: "Dark Green",
      colour2: "Forest",
      color: "Verde Oscuro",
      mbti: "-NTP",
      location: "Field",
      localidad: "Campo",
      map: "Research Center, Journal, Excursion",
      mapa: "Centro de Investigación, Excursión"
  },
  "011": {
      code: "011",
      adjective: "Ideational",
      adjectivo: "Ideacional",
      concept: "Creativity",
      concepto: "Creatividad",
      archetype: "Storyteller",
      arquetipo: "Cuentacuentos",
      colour: "Dark Cyan",
      colour2: "Teal",
      color: "Verde Azulado",
      mbti: "EN-P",
      location: "Cafe",
      localidad: "Café",
      map: "Dialogue, Lecture, Publication",
      mapa: "Diálogo, Lectura, Publicación"
  },
  "012": {
      code: "012",
      adjective: "Existential",
      adjectivo: "Existencial",
      concept: "Meaning",
      concepto: "Significado",
      archetype: "Counselor",
      arquetipo: "Consejero",
      colour: "Cyan Blue",
      colour2: "Aqua",
      color: "Azul Ciano",
      mbti: "-NF-",
      location: "Sanctuary",
      localidad: "Santuario",
      map: "Temple, Memorial, Museum",
      mapa: "Templo, Memorial, Museo"
  },
  "020": {
      code: "020",
      adjective: "Analytical",
      adjectivo: "Analítico",
      concept: "Reason",
      concepto: "Raciocinio",
      archetype: "Scientist",
      arquetipo: "Científico",
      colour: "Pure Green",
      colour2: "Lime",
      color: "Verde Puro",
      mbti: "INTP",
      location: "Study",
      localidad: "Estudio",
      map: "Desk, Board, Observatory",
      mapa: "Escritorio, Pizzarra, Observatorio"
  },
  "021": {
      code: "021",
      adjective: "Theoretical",
      adjectivo: "Teórica",
      concept: "Plans",
      concepto: "Planeación",
      archetype: "Instructor",
      arquetipo: "Instructor",
      colour: "Cyan Green",
      colour2: "Emerald",
      color: "Verde Ciano",
      mbti: "-NT-",
      location: "Seminar",
      localidad: "Seminario",
      map: "Forum, Expo, Classroom",
      mapa: "Forum, Expo, Aula"
  },
  "022": {
      code: "022",
      adjective: "Ethical",
      adjectivo: "Ético",
      concept: "Morals",
      concepto: "Moralidad",
      archetype: "Philosopher",
      arquetipo: "Filosófo",
      colour: "Pure Cyan",
      colour2: "Turquoise",
      color: "Ciano Puro",
      mbti: "IN-J",
      location: "Library",
      localidad: "Biblioteca",
      map: "Rectory, Seminar, History",
      mapa: "Archivos, Mentoría, Historia"
  },
  "100": {
      code: "100",
      adjective: "Sensorial",
      adjectivo: "Sensorial",
      concept: "Alertness",
      concepto: "Alerta",
      archetype: "Scout",
      arquetipo: "Explorador",
      colour: "Dark Red",
      colour2: "Maroon",
      color: "Rojo Oscuro",
      mbti: "-S-P",
      location: "Field",
      localidad: "Campo",
      map: "Park, Hunting Ground, Yard",
      mapa: "Deportes De Campo, Cacería, Parque"
  },
  "101": {
      code: "101",
      adjective: "Jovial",
      adjectivo: "Jovial",
      concept: "Mood",
      concepto: "Humor",
      archetype: "Entertainer",
      arquetipo: "Animador",
      colour: "Dark Magenta",
      colour2: "Purple",
      color: "Magenta Oscuro",
      mbti: "ESFP",
      location: "Club",
      localidad: "Club",
      map: "Cafeteria, Bar, Party Area",
      mapa: "Cafetería, Bar, Salón De Fiestas"
  },
  "102": {
      code: "102",
      adjective: "Sensual",
      adjectivo: "Sensual",
      concept: "Taste",
      concepto: "Gusto",
      archetype: "Designer",
      arquetipo: "Diseñador",
      colour: "Magenta Blue",
      colour2: "Violet",
      color: "Magenta Azul",
      mbti: "--F-",
      location: "Gallery",
      localidad: "Galería",
      map: "Restaurant, Art Exhibit, Runway",
      mapa: "Exhibición De Arte, Restaurant, Pasarela"
  },
  "110": {
      code: "110",
      adjective: "Factual",
      adjectivo: "Factual",
      concept: "Objectivity",
      concepto: "Objetividad",
      archetype: "Dealer",
      arquetipo: "Negociante",
      colour: "Dark Yellow",
      colour2: "Mustard",
      color: "Amarillo Oscuro",
      mbti: "ESTP",
      location: "Shop",
      localidad: "Tienda",
      map: "Market, Trading Floor, Casino",
      mapa: "Comercio, Banca, Casino"
  },
  "111": {
      code: "111",
      adjective: "Social",
      adjectivo: "Social",
      concept: "Communication",
      concepto: "Comunicación",
      archetype: "Messenger",
      arquetipo: "Comunicador",
      colour: "Neutral",
      colour2: "Gray",
      color: "Gris",
      mbti: "E---",
      location: "Plaza",
      localidad: "Plaza",
      map: "Hallway, Media, Main Hub",
      mapa: "Pasillo, Medios De Comunciación, Centro"
  },
  "112": {
      code: "112",
      adjective: "Congenial",
      adjectivo: "Congenial",
      concept: "Relationships",
      concepto: "Vínculos",
      archetype: "Diplomat",
      arquetipo: "Diplomático",
      colour: "Light Blue",
      colour2: "Lavender",
      color: "Azul Claro",
      mbti: "ENFJ",
      location: "Community Center",
      localidad: "Centro Comunitario",
      map: "Cultural Center, Embassy, Hospitality",
      mapa: "Centro Cultural, Embajada, Hotelería"
  },
  "120": {
      code: "120",
      adjective: "Technical",
      adjectivo: "Técnico",
      concept: "Functionality",
      concepto: "Funcionalidad",
      archetype: "Technitian",
      arquetipo: "Técnico",
      colour: "Yellow Green",
      colour2: "Chartreuse",
      color: "Verde Amarillo",
      mbti: "--T-",
      location: "Lab",
      localidad: "Laboratorio",
      map: "Systems, Technology, Accounting",
      mapa: "Sistemas, Tecnología, Contabilidad"
  },
  "121": {
      code: "121",
      adjective: "Organizational",
      adjectivo: "Organizacional",
      concept: "Logistics",
      concepto: "Logística",
      archetype: "Director",
      arquetipo: "Director",
      colour: "Light Green",
      colour2: "Mint",
      color: "Verde Claro",
      mbti: "ENTJ",
      location: "Civic Center",
      localidad: "Centro Civil",
      map: "Organization, Club, Politic Arena",
      mapa: "Organización, Club, Arena Política"
  },
  "122": {
      code: "122",
      adjective: "Critical",
      adjectivo: "Crítico",
      concept: "Order",
      concepto: "Orden",
      archetype: "Judge",
      arquetipo: "Juez",
      colour: "Light Cyan",
      colour2: "Sky",
      color: "Ciano Claro",
      mbti: "-N-J",
      location: "Court",
      localidad: "Corte",
      map: "Assembly, Advisory, Congress",
      mapa: "Asamblea, Consejería, Congreso"
  },
  "200": {
      code: "200",
      adjective: "Martial",
      adjectivo: "Marcial",
      concept: "Action",
      concepto: "Acción",
      archetype: "Athlete",
      arquetipo: "Atleta",
      colour: "Pure Red",
      colour2: "Scarlet",
      color: "Rojo Puro",
      mbti: "IS-P",
      location: "Arena",
      localidad: "Arena",
      map: "Stadium, Dojo, Track & Field",
      mapa: "Estadio, Dojo, Campo Y Pista"
  },
  "201": {
      code: "201",
      adjective: "Sensational",
      adjectivo: "Sensacional",
      concept: "Attitude",
      concepto: "Actitud",
      archetype: "Performer",
      arquetipo: "Estrella",
      colour: "Magenta Red",
      colour2: "Pink",
      color: "Rojo Magenta",
      mbti: "-SF-",
      location: "Gym",
      localidad: "Gimnasio",
      map: "Ring, Stage, Dance Floor",
      mapa: "Pista, Escenario, Salón De Baile"
  },
  "202": {
      code: "202",
      adjective: "Devotional",
      adjectivo: "Devocional",
      concept: "Passion",
      concepto: "Passion",
      archetype: "Artiste",
      arquetipo: "Artista",
      colour: "Pure Magenta",
      colour2: "Fuchsia",
      color: "Magenta Puro",
      mbti: "ISFJ",
      location: "Studio",
      localidad: "Atelier",
      map: "Atelier, Crafts, Kitchen",
      mapa: "Artesanía, Cocina, Manualidades"
  },
  "210": {
      code: "210",
      adjective: "Practical",
      adjectivo: "Práctico",
      concept: "Aptitude",
      concepto: "Aptitud",
      archetype: "Maker",
      arquetipo: "Fabricante",
      colour: "Yellow Red",
      colour2: "Orange",
      color: "Rojo Amarillo",
      mbti: "-ST-",
      location: "Workshop",
      localidad: "Taller",
      map: "Warehouse, Garage, Construction",
      mapa: "Almacen, Garage, Construcción"
  },
  "211": {
      code: "211",
      adjective: "Diligent",
      adjectivo: "Diligente",
      concept: "Service",
      concepto: "Servicio",
      archetype: "Agent",
      arquetipo: "Agente",
      colour: "Light Red",
      colour2: "Coral",
      color: "Rojo Claro",
      mbti: "ES-J",
      location: "Service Center",
      localidad: "Centro De Servicio",
      map: "Security, Life Guarding, Agency",
      mapa: "Seguridad, Agencia, Superintendencia"
  },
  "212": {
      code: "212",
      adjective: "Protectoral",
      adjectivo: "Protectoral",
      concept: "Security",
      concepto: "Seguridad",
      archetype: "Protector",
      arquetipo: "Protector",
      colour: "Light Magenta",
      colour2: "Rose",
      color: "Magenta Claro",
      mbti: "-SFJ",
      location: "Clinic",
      localidad: "Clínica",
      map: "Aid, Health, Care Center",
      mapa: "Asistencia, Centro De Salud, Guardería"
  },
  "220": {
      code: "220",
      adjective: "Industrial",
      adjectivo: "Industrial",
      concept: "Productivity",
      concepto: "Productividad",
      archetype: "Engineer",
      arquetipo: "Ingeniero",
      colour: "Pure Yellow",
      colour2: "Canary",
      color: "Amarillo Puro",
      mbti: "ISTJ",
      location: "Industry",
      localidad: "Industria",
      map: "Factory, Engineering, Manufactoring",
      mapa: "Fábrica, Ingeniería, Manufactura"
  },
  "221": {
      code: "221",
      adjective: "Motivational",
      adjectivo: "Motivacional",
      concept: "Goals",
      concepto: "Propósitos",
      archetype: "Manager",
      arquetipo: "Manager",
      colour: "Light Yellow",
      colour2: "Cream",
      color: "Amarillo Claro",
      mbti: "-STJ",
      location: "Company",
      localidad: "Compañía",
      map: "Venture, Business, Enterprise",
      mapa: "Projectos, Negocios, Empresas"
  },
  "222": {
      code: "222",
      adjective: "Imperial",
      adjectivo: "Imperial",
      concept: "Control",
      concepto: "Control",
      archetype: "Cheif",
      arquetipo: "Jefe",
      colour: "Light",
      colour2: "Pearl",
      color: "Blanco",
      mbti: "I--J",
      location: "Management",
      localidad: "Gerencia",
      map: "Palace, Tribune, Government",
      mapa: "Palacio, Tribunal, Gobierno"
  }
}

export default states;